# Generated by Django 4.0.2 on 2024-02-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoname', models.CharField(max_length=191)),
                ('foodName', models.CharField(max_length=191)),
                ('mobile', models.CharField(max_length=40)),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('companyName', models.CharField(max_length=191)),
                ('number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('foodName', models.CharField(max_length=191)),
                ('foodImage', models.ImageField(blank=True, null=True, upload_to='static/pics')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Both', 'Both')], max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
                ('donationdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ferti_Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertiname', models.CharField(max_length=191)),
                ('foodName', models.CharField(max_length=191)),
                ('mobile', models.CharField(max_length=40)),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='food', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NGOExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Reg_Id', models.CharField(max_length=4)),
                ('Email_id', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonarExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=191)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40)),
                ('fssi_certificate', models.ImageField(upload_to='cerificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
